from flask import Flask, render_template, jsonify, request
from context import Context

app = Flask(__name__, template_folder='static/templates')
context = None


@app.route('/endGame')
def endGame():
    return render_template('endGame.html')

@app.route('/runGame', methods=['GET','POST'])
def runGame():
    data = request.get_json()
    current_context = Context(data['initial_theme'])
    # data = response generated by chatGPT
    ammended_context = current_context.update_context(data)
    return render_template('runGame.html',  context=ammended_context)
    

@app.route('/startGame')
def startGame():
    return render_template('startGame.html')

@app.route('/')
def home():
    return render_template('index.html')

if __name__ == '__main__':
    app.run(debug=True)